// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterAnimationFrame } from "./CharacterAnimationFrame";

export interface Animation { current_frame_time_in_ms: number, current_total_time_in_ms: number, animation_total_duration: number, frames: Array<CharacterAnimationFrame>, current_frame_index: number, running: boolean, done: boolean, }