// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceKind } from "./ResourceKind";

export interface BlueprintResource { file_name: string, dir: string, path: string, kind: ResourceKind, }