// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RigidBody } from "./RigidBody";

export type BodyType = "None" | { RigidBody: RigidBody };