// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Physicality } from "./Physicality";
import type { Render } from "./Render";

export interface Body { physicality: Physicality, render: Render, children: Array<Body>, }