// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CameraSettings { zoom: number, bounds: [[number, number], [number, number]] | null, }