// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ChunkUpdate { position: [number, number], tile_updates: Record<number, Record<number, number>>, }