// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Chunk { width: number, height: number, position: [number, number], data: Array<Array<number>>, }