// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollisionShape = { Rectangle: [number, number, number, number] } | { Circle: [number, number, number] } | { Polygon: Array<[number, number]> };