// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RigidBodyType } from "./RigidBodyType";
import type { ScopeCacheValue } from "./ScopeCacheValue";
import type { Transform } from "./Transform";

export type EntityUpdateKind = { Transform: Transform } | { Name: string } | { InstancePath: string } | { ScriptPath: string | null } | { UpdateScriptScope: [string, ScopeCacheValue] } | { SetScriptScope: Record<string, ScopeCacheValue> } | { RigidBodyType: RigidBodyType } | { PositionRotation: [number, number, number] } | { Gid: number };