// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";
import type { EntityUpdateKind } from "./EntityUpdateKind";

export interface EntityUpdate { id: Entity, kind: EntityUpdateKind, }