// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";

export interface FileBrowserResult { path: string, dir: string, dirs: Array<string>, resources: Array<Resource>, }