// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameNode } from "./GameNode";
import type { Physicality } from "./Physicality";

export type GameNodeKind = { Scene: string } | { Group: GameNode<string> } | { Physics: GameNode<Physicality> } | { Render: GameNode<Physicality> };