// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameNode } from "./GameNode";
import type { Node2D } from "./Node2D";

export type GameNodeKind = { Instance: GameNode<string> } | { Node2D: GameNode<Node2D> };