// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameNodeKind } from "./GameNodeKind";

export interface GameNode<T> { id: string, name: string, inherits: string | null, data: T, children: Array<GameNodeKind>, }