// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chunk } from "./Chunk";
import type { Entity } from "./Entity";
import type { LayerKind } from "./LayerKind";

export interface MapUpdate { name: string, resource_path: string, entities: Array<Entity> | null, chunk: [LayerKind, Chunk] | null, }