// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueprintResource } from "./BlueprintResource";
import type { GidMap } from "./GidMap";
import type { IOPoint } from "./IOPoint";

export interface Module { id: string, name: string, resources: Array<BlueprintResource>, main_map: string | null, gid_map: GidMap, insert_points: Array<IOPoint>, exit_points: Array<IOPoint>, max_guests: number, min_guests: number, close_after_full: boolean, }