// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueprintResource } from "./BlueprintResource";
import type { IOPoint } from "./IOPoint";

export interface ModuleUpdate { name: string | null, resources: Array<BlueprintResource> | null, insert_points: Array<IOPoint> | null, exit_points: Array<IOPoint> | null, max_guests: number | null, min_guests: number | null, }