// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Collider } from "./Collider";
import type { Render } from "./Render";
import type { RigidBody } from "./RigidBody";

export type Node2DKind = "Node2D" | { RigidBody: RigidBody } | { Collider: Collider } | { Render: Render };