// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Collider } from "./Collider";
import type { Node2DDud } from "./Node2DDud";
import type { Render } from "./Render";
import type { RigidBody } from "./RigidBody";

export type Node2DKind = { Instance: string } | { Node2D: Node2DDud } | { RigidBody: RigidBody } | { Collider: Collider } | { Render: Render };