// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerKind } from "./LayerKind";
import type { RenderKind } from "./RenderKind";

export interface Render { offset: [number, number], layer: LayerKind, kind: RenderKind, }