// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TerrainParams { chunk_size: number, tile_width: number, tile_height: number, }