// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationFrame } from "./AnimationFrame";
import type { CollisionShape } from "./CollisionShape";
import type { Image } from "./Image";

export interface Tile { id: number, image: Image | null, animation: Array<AnimationFrame> | null, collision_shape: CollisionShape | null, }