// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraSettings } from "./CameraSettings";
import type { Entity } from "./Entity";
import type { TerrainParams } from "./TerrainParams";

export interface WorldParams { terrain_params: TerrainParams, camera_settings: CameraSettings, camera_ref: Entity | null, }