// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminResourceCud<C, U = C, D = U> = { Create: C } | { Update: U } | { Delete: D };