// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conductor } from "../blueprints/Conductor";
import type { ModuleUpdate } from "../blueprints/ModuleUpdate";
import type { ProviderLoggedIn } from "./ProviderLoggedIn";

export type AdminToSystemEvent = { ProviderLoggedIn: ProviderLoggedIn } | { UpdateConductor: Conductor } | { UpdateModule: [string, ModuleUpdate] } | { CreateModule: string } | { DeleteModule: string } | { SetMainDoorStatus: boolean } | { SetBackDoorStatus: boolean } | "LoadEditorData" | "Ping";