// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminResourceCud } from "./AdminResourceCud";
import type { Audio } from "../blueprints/Audio";
import type { Font } from "../blueprints/Font";

export type CudResource = { Audio: [string, AdminResourceCud<Audio>] } | { Font: [string, AdminResourceCud<Font>] };