// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Audio } from "../blueprints/Audio";
import type { EditorCsd } from "./EditorCsd";
import type { Font } from "../blueprints/Font";

export type EditorResource = { Audio: EditorCsd<Audio> } | { Font: EditorCsd<Font> };