// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conductor } from "../blueprints/Conductor";
import type { FileBrowserResult } from "../blueprints/FileBrowserResult";
import type { GameMap } from "../blueprints/GameMap";
import type { MapUpdate } from "../blueprints/MapUpdate";
import type { Module } from "../blueprints/Module";
import type { Tileset } from "../blueprints/Tileset";

export type EditorEvent = { "Modules": Array<Module> } | { "ModuleInstances": Array<[string, Array<string>]> } | { "CreatedModule": [string, Module] } | { "DeletedModule": string } | { "UpdatedModule": [string, Module] } | { "CreatedMap": GameMap } | { "SetMap": GameMap } | { "UpdatedMap": [string, MapUpdate] } | { "DeletedMap": GameMap } | { "CreatedTileset": Tileset } | { "SetTileset": Tileset } | { "DeletedTileset": Tileset } | { "DirectoryInfo": FileBrowserResult } | { "UpdatedConductor": Conductor } | { "ModuleInstanceOpened": [string, string] } | { "ModuleInstanceClosed": [string, string] } | { "MainDoorStatus": boolean };