// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conductor } from "../blueprints/Conductor";
import type { Module } from "../blueprints/Module";
import type { Tileset } from "../blueprints/Tileset";

export type EditorEvent = { Modules: Array<Module> } | { CreatedModule: [string, Module] } | { DeletedModule: string } | { UpdatedModule: [string, Module] } | { CreatedTileset: Tileset } | { UpdatedTileset: Tileset } | { DeletedTileset: Tileset } | { UpdatedConductor: Conductor } | { MainDoorStatus: boolean };