// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoRender } from "./NoRender";
import type { RenderTypeText } from "./RenderTypeText";
import type { RenderTypeTimer } from "./RenderTypeTimer";
import type { StaticImage } from "./StaticImage";

export type EntityRenderData = { "StaticImage": StaticImage } | { "RenderTypeTimer": RenderTypeTimer } | { "RenderTypeText": RenderTypeText } | { "NoRender": NoRender };