// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorEvent } from "./EditorEvent";
import type { GameSystemToGuestEvent } from "./GameSystemToGuestEvent";
import type { ResourceBundle } from "./ResourceBundle";
import type { ResourceEvent } from "./ResourceEvent";
import type { SignalToMedium } from "./SignalToMedium";
import type { ToastAlertLevel } from "./ToastAlertLevel";

export type CommunicationEvent = { "ResourceEvent": [string, ResourceEvent] } | { "PrepareGame": [string, string, ResourceBundle, boolean] } | { "GameSystemEvent": [string, string, GameSystemToGuestEvent] } | { "PositionEvent": [string, string, Array<[string, number, number, number]>] } | { "ConnectionReady": [string, boolean] } | { "Signal": SignalToMedium } | { "Toast": [ToastAlertLevel, string] } | { "ShowGlobalMessage": string } | "AlreadyConnected" | { "EditorEvent": EditorEvent };