// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSystemToGuestEvent } from "./GameSystemToGuestEvent";
import type { ResourceEvent } from "./ResourceEvent";
import type { SignalToGuest } from "./SignalToGuest";
import type { ToastAlertLevel } from "./ToastAlertLevel";

export type CommunicationEvent = { ResourceEvent: ResourceEvent } | { GameSystemEvent: GameSystemToGuestEvent } | { PositionEvent: Array<[string, number, number, number]> } | { ConnectionReady: [string, boolean] } | { Signal: SignalToGuest } | { Toast: [ToastAlertLevel, string] } | { ShowGlobalMessage: string } | "AlreadyConnected";