// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraSettings } from "./CameraSettings";
import type { LayerName } from "./LayerName";
import type { MouseInputSchema } from "./MouseInputSchema";
import type { RemoveEntity } from "./RemoveEntity";
import type { ShowEffect } from "./ShowEffect";
import type { ShowEntity } from "./ShowEntity";
import type { TerrainChunk } from "./TerrainChunk";
import type { UpdateEntity } from "./UpdateEntity";

export type GameSystemToGuestEvent = { "OpenMenu": string } | { "CloseMenu": string } | { "UpdateDataStore": string } | { "ShowTerrainChunks": [number, Array<TerrainChunk>] } | { "SetParallax": Array<[LayerName, [number, number]]> } | { "ShowEntities": Array<ShowEntity> } | { "ShowEffects": Array<ShowEffect> } | { "UpdateEntities": Array<UpdateEntity> } | { "RemoveEntities": Array<RemoveEntity> } | "RemoveAllEntities" | { "SetMouseInputSchema": MouseInputSchema } | { "ChangeEntity": Array<ShowEntity> } | { "SetCamera": [string, CameraSettings] };