// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CameraSettings } from "./CameraSettings";
import type { Chunk } from "../blueprints/Chunk";
import type { Entity } from "../blueprints/Entity";
import type { EntityUpdate } from "../blueprints/EntityUpdate";
import type { GameNodeKind } from "../blueprints/GameNodeKind";
import type { LayerKind } from "../blueprints/LayerKind";
import type { MouseInputSchema } from "./MouseInputSchema";
import type { Scene } from "../blueprints/Scene";

export type GameSystemToGuestEvent = { OpenMenu: string } | { CloseMenu: string } | { UpdateDataStore: string } | { ShowTerrain: Array<[LayerKind, Array<Chunk>]> } | { SetParallax: Array<[LayerKind, number, number]> } | { ShowTerrainCollisionLines: Array<Array<[number, number]>> } | { ShowScene: Scene } | { UpdateEntity: EntityUpdate } | { RemoveEntity: Entity } | { AddEntity: [Entity, GameNodeKind] } | { SetMouseInputSchema: MouseInputSchema } | { SetCamera: [string, CameraSettings] } | { PositionEvent: Array<[Entity, number, number, number]> };