// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuestToModuleEvent } from "./GuestToModuleEvent";
import type { GuestToSystemEvent } from "./GuestToSystemEvent";

export type GuestTo = { GuestToSystemEvent: GuestToSystemEvent } | { GuestToModuleEvent: GuestToModuleEvent };