// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadResourceKind } from "./LoadResourceKind";

export interface LoadResource { kind: LoadResourceKind, path: string, cache_hash: string, }