// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginProvider } from "./LoginProvider";

export interface LoginData { provider_user_id: string, display_name: string, views: number | null, provider: LoginProvider, }