// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretFoundEntry } from "./SecretFoundEntry";

export interface MediumDataStorageGuestInfo { guests_online: number, guest_name: string, times_joined: number, secrets_found_count: number, secrets_found_map: Record<string, SecretFoundEntry>, }