// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediumDataStorageGuestInfo } from "./MediumDataStorageGuestInfo";

export interface MediumDataStorage { current_guest_info: MediumDataStorageGuestInfo | null, }