// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginProvider } from "./LoginProvider";

export interface ProviderLoggedIn { auth_code: string | null, access_token: string | null, login_provider: LoginProvider, }