// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerName } from "./LayerName";

export interface RenderTypeTimer { date: string, font_family: string, color: string, layer: LayerName, }