// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceKind } from "./ResourceKind";

export interface Resource { meta_name: string, kind: ResourceKind, path: string, cache_hash: bigint, }