// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceMap } from "./ResourceMap";

export type ResourceEvent = { LoadResource: ResourceMap } | { UnLoadResource: string };