// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadResource } from "./LoadResource";

export interface ResourceBundle { name: string, assets: Array<LoadResource>, }