// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GidMap } from "../blueprints/GidMap";
import type { ResourceBundle } from "./ResourceBundle";
import type { Tileset } from "../blueprints/Tileset";

export type ResourceEvent = { LoadTilesets: Array<Tileset> } | { UpdateGidMap: GidMap } | { LoadResource: ResourceBundle } | "UnLoadResources";