// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceBundle } from "./ResourceBundle";

export type ResourceEvent = { "LoadResource": ResourceBundle } | "UnLoadResource";