// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TileSetResourceDef } from "./TileSetResourceDef";

export type ResourceKind = "Menu" | "Image" | "Font" | { "TileSet": TileSetResourceDef } | "Sound";