// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityUpdateKind } from "../blueprints/EntityUpdateKind";
import type { GameNodeKind } from "../blueprints/GameNodeKind";

export type SceneNodeUpdate = { UpdateData: [string, Array<number>, string, EntityUpdateKind] } | { AddChild: [string, Array<number>, string, GameNodeKind] } | { RemoveChild: [string, Array<number>, GameNodeKind] };