// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ShakeScreenEffect { shake_amount: number, shake_delay: number, shake_count_max: number, is_bidirectional: boolean, }