// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShakeScreenEffect } from "./ShakeScreenEffect";
import type { SimpleImageEffect } from "./SimpleImageEffect";

export type ShowEffect = { SimpleImageEffect: SimpleImageEffect } | { ShakeScreenEffect: ShakeScreenEffect };