// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerName } from "./LayerName";

export interface TerrainChunk { x: number, y: number, width: number, height: number, tile_ids: Array<Array<number>>, layer: LayerName, }