// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollisionShape } from "../blueprints/CollisionShape";

export type TileUpdate = { UpdateCollisionShape: [number, CollisionShape] };