// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chunk } from "./Chunk";
import type { Entity } from "./Entity";
import type { Joint } from "./Joint";
import type { LayerKind } from "./LayerKind";
import type { Resource } from "./Resource";

export interface Map { name: string, resources: Array<Resource>, entities: Array<Entity>, joints: Record<number, Joint>, terrain: Record<LayerKind, Array<Chunk>>, }