// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AutoStepProps { max_height: number, min_width: number, include_dynamic_bodies: boolean, }