// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterDirection } from "./CharacterDirection";

export interface CharacterAnimationFrame { duration_in_ms: number, gid_map: Record<CharacterDirection, number>, }