// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CharacterTransitionFunctions { name: string, possible_transitions: Record<bigint, bigint>, }