// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColliderShape = { Ball: number } | { CapsuleX: [number, number] } | { CapsuleY: [number, number] } | { Cuboid: [number, number] };