// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColliderKind } from "./ColliderKind";
import type { ColliderShape } from "./ColliderShape";

export interface Collider { kind: ColliderKind, shape: ColliderShape, }