// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlueprintResource } from "./BlueprintResource";
import type { GidMap } from "./GidMap";

export interface Conductor { module_connection_map: Record<string, [string, string]>, resources: Array<BlueprintResource>, gid_map: GidMap, }