// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resource } from "./Resource";

export interface Conductor { module_connection_map: Record<string, [string, string]>, resources: Array<Resource>, gid_map: Array<[string, number]>, }