// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DynamicRigidBodyProps { gravity_scale: number, can_sleep: boolean, ccd_enabled: boolean, linear_dampening: number, angular_dampening: number, rotation_locked: boolean, }