// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DynamicRigidBodyPropsUpdate { gravity_scale: number | null, can_sleep: boolean | null, ccd_enabled: boolean | null, linear_dampening: number | null, angular_dampening: number | null, rotation_locked: boolean | null, }