// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameNodeKind } from "./GameNodeKind";

export interface GameNodeInheritance { parent_id: string, overrides: Record<string, GameNodeKind>, }