// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoStepProps } from "./AutoStepProps";

export interface KinematicCharacterControllerProps { offset: number, up: [number, number], slide: boolean, autostep: AutoStepProps | null, max_slope_climb_angle: number, min_slope_slide_angle: number, snap_to_ground: number | null, normal_nudge_factor: number, }