// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayerKind } from "./LayerKind";

export interface Layer { name: string, kind: LayerKind, }