// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayerKind = "BG10" | "BG09" | "BG08" | "BG07" | "BG06" | "BG05" | "BG04" | "BG03" | "BG02" | "BG01" | "BG00" | "ObjectsBelow" | "Terrain" | "ObjectsFront" | "FG00" | "FG01" | "FG02" | "FG03" | "FG04" | "FG05" | "FG06" | "FG07" | "FG08" | "FG09" | "FG10" | "UI";