// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IOPoint } from "./IOPoint";
import type { Map } from "./Map";
import type { Resource } from "./Resource";

export interface ModuleUpdate { name: string | null, resources: Array<Resource> | null, maps: Array<Map> | null, insert_points: Array<IOPoint> | null, exit_points: Array<IOPoint> | null, max_guests: number | null, min_guests: number | null, }