// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IOPoint } from "./IOPoint";
import type { Map } from "./Map";
import type { Resource } from "./Resource";

export interface Module { name: string, resources: Array<Resource>, maps: Array<Map>, insert_points: Array<IOPoint>, exit_points: Array<IOPoint>, max_guests: number, min_guests: number, close_after_full: boolean, }