// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Node2DKind } from "./Node2DKind";
import type { Transform } from "./Transform";

export interface Node2D { transform: Transform, kind: Node2DKind, }