// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BodyType } from "./BodyType";

export interface Physicality { position: [number, number], velocity: [number, number], rotation: number, body: BodyType, }