// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProgressBar { progress: number, tileset: string, background: number, fill: number, fill_paddings: [number, number, number, number], width: number, height: number, }