// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProgressBarUpdate { tileset: string | null, background: number | null, fill: number | null, fill_paddings: [number, number, number, number] | null, progress: number | null, width: number | null, height: number | null, }