// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressBar } from "./ProgressBar";
import type { TextRender } from "./TextRender";

export type RenderKind = { AnimatedSprite: [string, number] } | { Sprite: [string, number] } | { Text: TextRender } | { ProgressBar: ProgressBar };