// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RigidBodyType } from "./RigidBodyType";

export interface RigidBody { position: [number, number], velocity: [number, number], rotation: number, body: RigidBodyType, }