// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicRigidBodyProps } from "./DynamicRigidBodyProps";
import type { KinematicCharacterControllerProps } from "./KinematicCharacterControllerProps";
import type { RigidBodyType } from "./RigidBodyType";

export interface RigidBody { kinematic_character_controller_props: KinematicCharacterControllerProps | null, dynamic_rigid_body_props: DynamicRigidBodyProps | null, body: RigidBodyType, }