// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollisionShape } from "./CollisionShape";

export interface RigidBody { collision_shape: CollisionShape, joints: Array<number>, }