// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameNodeKind } from "./GameNodeKind";

export interface Scene { id: string, name: string, resource_path: string, root_node: GameNodeKind, }