// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";

export type ScopeCacheValue = { Unknown: string } | "Empty" | { String: string } | { Number: number } | { Integer: bigint } | { Entity: Entity } | { Map: Record<string, ScopeCacheValue> };