// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextRenderAlignment } from "./TextRenderAlignment";

export interface TextRender { text: string, font_family: string, size: number, align: TextRenderAlignment, }