// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollisionShape } from "./CollisionShape";
import type { Image } from "./Image";
import type { SimpleAnimationFrame } from "./SimpleAnimationFrame";

export interface Tile { id: number, image: Image | null, loop_animation: boolean | null, animation: Array<SimpleAnimationFrame> | null, collision_shape: CollisionShape | null, }