// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Transform { position: [number, number], scale: [number, number], velocity: [number, number], rotation: number, }